Task/109 secure pin functionality
SimplioOfficial/simplio-app pull request #121
Opened 2022-07-28 15:02 UTC by storkandstars

# Overview

Task implements application protection via a security secret that is generated on account creation. This secret is encrypted with a user defined pin. We use a AES encryption algo that generates and stores a unique iv number.

There was a large migration from a Navigator to Router. Implementation of Router is via [go_router](https://gorouter.dev/).

## Test cases

#### 1. Creating a security pin

- When there is an initial login on a device a user is redirected to a pin setup screen.
- User inserts 4 digit pin
- A square submit button appears
- After submit a user is redirected to a success screen (Both these screens cannot be left by clicking on back button or lading back)
- After clicking on `start using app` user enters the dashboard.
- During setting up a security pin, a user is always returned to the setup pin screen after he leaves the entire app.

#### 2. Verifying a security pin

- When a security pin is set on a device the user is asked to enter the pin on app enter.
- if the pin is correct, the user is brought into dashboard when the form gets 4 digit pin
- if the user enters incorrect pin, a remaining attempts message appears under pin input
- if the user leaves the app and comes back, the remaining attempts appears with the last seen value
- After correct pin enter, remaining attempts are reset to the initial value (that is by default 6)
- If the user enters 6 times pin incorrecly, he is log out.
 
#### 3. Protected screens

- going to the settings/configuration screen there is a protected screen `password change`. After going to that screen, the user should be asked to verify his pin.
- If the pin is 6 time incorrectly entered, the user is pushed to the previous screen

2022-08-03 11:51 UTC, jvrastil requested changes

2022-08-03 11:51 UTC, jvrastil commented on lib/view/screens/application_screen.dart
> +                            // ApplicationRoute.key.currentState
remove unused code please

2022-08-03 11:51 UTC, jvrastil commented on lib/view/screens/dashboard_screen.dart
> +                  // ApplicationRoute.key.currentState
remove unused code here as well please

2022-08-03 11:51 UTC, jvrastil commented on lib/view/screens/portfolio_screen.dart
> +                          //   ApplicationRoute.key.currentState?.pushNamed(
should't we redirect user with new router or is it prepared for some future task?

2022-08-03 11:51 UTC, jvrastil commented on lib/view/widgets/keypad.dart
> +                // children: row.children,
remove

2022-08-03 11:51 UTC, jvrastil commented on lib/view/widgets/keypad.dart
> +      // stretchItems: true,
remove this as well please

2022-08-03 11:51 UTC, jvrastil commented on lib/view/widgets/pin_digits.dart
> +    this.duration = const Duration(milliseconds: 0),
is this supposed to be 0 when default style is `hideAllAfterTime` ?

2022-08-03 11:51 UTC, jvrastil commented on lib/view/widgets/pin_digits.dart
> +      // mainAxisAlignment: MainAxisAlignment.center,
you can remove this as well

2022-08-04 08:11 UTC, storkandstars commented on .gitignore
> -## generated files
There was a duplicity in comments for generated files. At the bottom of the gitignore file there is definition for ignoring generated files provided from PR.

2022-08-04 08:13 UTC, storkandstars commented on lib/data/model/account_wallet.dart
> +    // TODO - Change IV value!
This section will we changed in issue #116 where we implement seed encryption.

2022-08-04 08:19 UTC, storkandstars commented on lib/data/repositories/auth_repository.dart
> +        final userId = decodedIdToken['sub'];
Yes. It was fixed. [0e90f10](https://github.com/SimplioOfficial/simplio-app/pull/121/commits/0e90f10443baaf60297e7746d8f4a026f8146fa4)

2022-08-04 08:22 UTC, storkandstars commented on lib/view/routes/guards/protected_guard.dart
> +                          style: const TextStyle(color: Colors.red),
It was fixed. [e1a34bd](https://github.com/SimplioOfficial/simplio-app/pull/121/commits/e1a34bd3319fe73819cdeb9a1ff9469d62e21d73)

2022-08-04 08:24 UTC, storkandstars commented on lib/logic/cubit/sign_up_form/sign_up_form_state.dart
> +// class SignInForm extends Equatable {
It was fixed. [1a58353](https://github.com/SimplioOfficial/simplio-app/pull/121/commits/1a58353109d756b42fd57a71835178b080249dfb)

2022-08-04 08:28 UTC, storkandstars commented on lib/view/authenticated_app.dart
> +              // _setSystemUIOverlayStyle(context);
Yes. By separating build context from router state. We are able to keep state of the router and remember screens on rebuild.
Comments are removed here [dda3c4b](https://github.com/SimplioOfficial/simplio-app/pull/121/commits/dda3c4b3e16a38b9dbf694a7d4ff437629066d9d)

2022-08-04 08:35 UTC, storkandstars commented on lib/view/widgets/pin_digits.dart
> +    this.duration = const Duration(milliseconds: 0),
Returned to the previous value [c4472b6](https://github.com/SimplioOfficial/simplio-app/pull/121/commits/c4472b6e36c52ecdb4a67fb422794ad1739cdae5)

2022-08-04 08:35 UTC, storkandstars commented on lib/view/widgets/pin_digits.dart
> +      // mainAxisAlignment: MainAxisAlignment.center,
Removed

2022-08-04 08:35 UTC, storkandstars commented on lib/view/widgets/keypad.dart
> +      // stretchItems: true,
Removed.

2022-08-04 08:36 UTC, storkandstars commented on lib/view/widgets/keypad.dart
> +                // children: row.children,
Removed.

2022-08-04 08:37 UTC, storkandstars commented on lib/view/screens/portfolio_screen.dart
> +                          //   ApplicationRoute.key.currentState?.pushNamed(
We can make an task with screen changes due to ux in future task.

2022-08-04 08:37 UTC, storkandstars commented on lib/view/screens/dashboard_screen.dart
> +                  // ApplicationRoute.key.currentState
Removed.

2022-08-04 08:38 UTC, storkandstars commented on lib/view/screens/application_screen.dart
> +                            // ApplicationRoute.key.currentState
Removed.

2022-08-04 08:38 UTC, storkandstars commented on lib/view/routes/authenticated_router.dart
> +            // final account = context.watch<AccountCubit>().state.account;
Removed.

2022-08-04 09:33 UTC, jvrastil approved these changes
looks good now 👍

2022-08-04 12:57 UTC, merged