Task/117 - Receive coins UI
SimplioOfficial/simplio-app pull request #126
Opened 2022-08-10 07:55 UTC by jvrastil

2022-08-16 10:24 UTC, storkandstars requested changes

2022-08-16 10:24 UTC, storkandstars commented on lib/view/routes/authenticated_router.dart
> +                    pageBuilder: (context, state) => NoTransitionPage(
Please use custom `pageBuilder` mixin method that is available.

2022-08-16 10:24 UTC, storkandstars commented on lib/view/routes/authenticated_router.dart
> +  AssetWallet? _getAssetWallet(state) {
Do not pollute router with logic other than redirection. Get the object through shared state from AccountWalletCubit or from go_router's extra param.

2022-08-16 10:24 UTC, storkandstars commented on lib/view/screens/asset_receive_screen.dart
> +  var displayPopupInfo = false;
UX designer should provide us with what type of notification we should use for these situation. We can use:
1. Local notifications
2. Toast message
3. Snack message (SnackBar)

Local solution is not reusable and will be hard to maintain.

2022-08-16 10:24 UTC, storkandstars commented on lib/data/model/account_wallet.dart
> +  String? getAddress(int assetId, int? networkAssetId) {
Account wallet should not get internal nested values. Keep the logic on related implementation layer.

2022-08-16 10:24 UTC, storkandstars commented on lib/view/screens/asset_send_screen.dart
> +class AssetSendScreen extends StatefulWidget {
Why is that a `StatefulWidget`? Prefer `StatelessWidget` if not necessary otherwise.

2022-08-16 11:15 UTC, storkandstars commented on lib/view/screens/asset_receive_screen.dart
> +  var displayPopupInfo = false;
UX recommended `toast` message but we are able to do it as `snack` message. It won't be necessary to keep toast persistent visibility.

2022-08-17 10:13 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +                    pageBuilder: (context, state) => NoTransitionPage(
Done - I modified the extension method in order to provide `state`

2022-08-17 10:14 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +  AssetWallet? _getAssetWallet(state) {
both methods are removed now

2022-08-17 10:14 UTC, jvrastil commented on lib/view/screens/asset_receive_screen.dart
> +  var displayPopupInfo = false;
I added `snack` message

2022-08-17 10:15 UTC, jvrastil commented on lib/view/screens/asset_send_screen.dart
> +class AssetSendScreen extends StatefulWidget {
Yes, it is remnant from previous development. It is fixed now

2022-08-17 10:49 UTC, jvrastil commented on lib/data/model/account_wallet.dart
> +  String? getAddress(int assetId, int? networkAssetId) {
done, moved to extension class

2022-08-17 14:10 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +                          selectedKey: const ValueKey(assetSend),
ok, removed

2022-08-17 14:12 UTC, jvrastil commented on lib/view/routes/mixins/asset_page_mixin.dart
> +mixin AssetPageMixin {
yes, I overlooked incorrect folder structure, thanks

2022-08-17 14:12 UTC, jvrastil commented on lib/view/routes/mixins/page_builder_mixin.dart
> +    if (child == null && childBuilder == null) {
it's resolved thanks to the next comment

2022-08-17 14:12 UTC, jvrastil commented on lib/view/routes/mixins/page_builder_mixin.dart
> +    Widget? Function(GoRouterState state)? childBuilder,
ok, I will simplify it and use builder everywhere

2022-08-17 14:13 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +  static final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
well not really but I placed it here since it's used across whole authenticated pages.  Or do you suggest better place for it?

2022-08-17 14:24 UTC, jvrastil commented on lib/view/screens/application_screen.dart
> +        IgnorePointer(
is it really problem for this case? I would suggest creating separated task for some more general solution

2022-08-20 20:51 UTC, storkandstars commented on lib/view/screens/application_screen.dart
> +        IgnorePointer(
We can plan reusable snack notifications for another task. In that case we should remove so we dont have dead code later.

2022-08-20 20:52 UTC, storkandstars commented on lib/view/routes/authenticated_router.dart
> +  static final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
authenticated_app if it is related to the initial scaffold in the tree.

2022-08-20 21:05 UTC, storkandstars commented on lib/view/screens/mixins/asset_page_mixin.dart
> +mixin AssetPageMixin {
Consider using more accurate name.

2022-08-22 07:47 UTC, jvrastil commented on lib/view/screens/asset_receive_screen.dart
> +          throw Exception('No AccountWallet Provided');
I am not sure it that can happened in real app because user navigates here from wallet. But just to be sure I added note to display the snackbar notification when we finish the task for it.

2022-08-22 07:48 UTC, jvrastil commented on lib/view/screens/application_screen.dart
> +        IgnorePointer(
ok, I will remove it and add todo notes

2022-08-22 07:49 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +  static final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
ok, but since the snackbar will be done in another task we can remove the key for now

2022-08-22 08:08 UTC, jvrastil commented on lib/view/screens/mixins/asset_page_mixin.dart
> +mixin AssetPageMixin {
ok

2022-08-22 20:31 UTC, storkandstars approved these changes

2022-08-23 10:12 UTC, merged