Task/116 create utxo wallet
SimplioOfficial/simplio-app pull request #128
Opened 2022-08-10 21:59 UTC by storkandstars

2022-08-12 18:52 UTC, jvrastil requested changes

2022-08-12 18:52 UTC, jvrastil commented on lib/view/routes/guards/protected_guard.dart
> +                          style: const TextStyle(color: Colors.red),
why did you revert this change?

2022-08-12 18:52 UTC, jvrastil commented on lib/view/screens/application_screen.dart
> +                            // ApplicationRoute.key.currentState
is this supposed to stay here?

2022-08-12 18:52 UTC, jvrastil commented on lib/view/widgets/asset_wallet_expansion_list.dart
> +                  vertical: 20.0,
there is `CommonTheme.verticalPadding`

2022-08-12 18:52 UTC, jvrastil commented on lib/view/widgets/crypto_asset_expansion_list.dart
> +                    const EdgeInsets.symmetric(vertical: 20.0, horizontal: 0),
same here

2022-08-12 18:52 UTC, jvrastil commented on lib/view/widgets/pin_digits.dart
> +    this.duration = const Duration(milliseconds: 0),
probably missed value from rebase

2022-08-12 18:52 UTC, jvrastil commented on lib/view/widgets/wallet_list_item.dart
>            padding: CommonTheme.padding,
is this widget still needed or can we remove it?

2022-08-12 19:58 UTC, storkandstars commented on lib/view/widgets/pin_digits.dart
> +    this.duration = const Duration(milliseconds: 0),
Yes. It was bad previous rebase. Fix [97795b0](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/97795b0ec18534415c10599e69f94646d83dcb36)

2022-08-12 20:00 UTC, storkandstars commented on lib/view/widgets/asset_wallet_expansion_list.dart
> +                  vertical: 20.0,
Fixed [f6a1f8e](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/f6a1f8e00c42b926e4ac43e68e7029bd5a0f360f)

2022-08-12 20:01 UTC, storkandstars commented on lib/view/widgets/crypto_asset_expansion_list.dart
> +                    const EdgeInsets.symmetric(vertical: 20.0, horizontal: 0),
Fixed [f6a1f8e](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/f6a1f8e00c42b926e4ac43e68e7029bd5a0f360f)

2022-08-12 20:02 UTC, storkandstars commented on lib/view/screens/application_screen.dart
> +                            // ApplicationRoute.key.currentState
Fixed [83373da](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/83373da74b02c12dad927705d72adadfece146f1)

2022-08-12 20:04 UTC, storkandstars commented on lib/view/routes/guards/protected_guard.dart
> +                          style: const TextStyle(color: Colors.red),
Fixed [9681d8c](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/9681d8c233b92c1b6294ceeabcfc2c2ca9f5fc6f)

2022-08-12 20:18 UTC, storkandstars commented on lib/data/model/account_wallet.dart
> +  LockableMnemonic.value({
Updated here [050d4a0](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/050d4a0b70df5cced1ef820d92f0183a643d92c2)

2022-08-12 20:30 UTC, storkandstars commented on lib/data/repositories/auth_repository.dart
> +  Future<Account> _resolveAccount(String accountId) async {
Updated here [8778695](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/8778695752924487286e716c938be933371188c7)

2022-08-12 20:33 UTC, storkandstars commented on .github/workflows/_test_application.yml
> +      - run: flutter test
We disgusted that we will return to previous test folder structure. Due to best practices.

2022-08-12 20:34 UTC, storkandstars commented on lib/view/widgets/wallet_list_item.dart
>            padding: CommonTheme.padding,
Removed [91a93fa](https://github.com/SimplioOfficial/simplio-app/pull/128/commits/91a93fae236157dc9c298a98a67eab3dbaebdb9a)

2022-08-13 10:17 UTC, jvrastil commented on .github/workflows/_test_application.yml
> +      - run: flutter test
ok, in that case you need to change `    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@test/fix_long_execution` into `    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/116-create-utxo-wallet` in file `.github/workflows/run_tests_on_pull_request.yml`

2022-08-14 13:34 UTC, storkandstars commented on .github/workflows/_test_application.yml
> +      - run: flutter test
Resolved b52d60e

2022-08-15 07:28 UTC, jvrastil approved these changes
looks good now 👍

2022-08-15 08:06 UTC, merged