Task/119 sending an asset logic
SimplioOfficial/simplio-app pull request #144
Opened 2022-08-19 06:44 UTC by ciripel

2022-08-19 07:12 UTC, TomasPetrik approved these changes

2022-08-19 08:33 UTC, jvrastil commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
foo this is super looong method 😨  Do you think it's possible to extract some parts and create smaller function blocks?

2022-08-19 14:54 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
As i can see it, the refactoring will reduce the size of the method only by a little. I will put all utils under specific methods. Will be done when i return Wednesday!

2022-08-20 20:44 UTC, storkandstars requested changes

2022-08-20 20:44 UTC, storkandstars commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
This function should be separated into logical segments. We will improve testability and maintainability.

2022-08-20 20:44 UTC, storkandstars commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
There should be methods for each type so this functions keeps only high level logic. Divide it into logical segments by asset type (eth, sio, utxo...) and broadcasting.

2022-08-20 20:44 UTC, storkandstars commented on lib/data/repositories/wallet_repository.dart
> +          walletAddress: _wallet.getAddressForCoin(networkId));
Anytime there is a use of `_wallet` at the beginning of execution context run `_checkInitializedAccountWallet ` and handle error.

2022-08-20 20:44 UTC, storkandstars commented on lib/data/repositories/wallet_repository.dart
> +    late sio.Transaction rawTransaction;
instead of using late we might have a logical method for building transactions and always returns rawTransaction. anytime we are able to have `final` value, we should consider using. That way it will be more predictable.

2022-08-20 20:44 UTC, storkandstars commented on packages/crypto_assets/lib/src/networks_groups.dart
> +class TWCoinType {
Should not this be part of sio core library? crypto_assets is more for styling purposes.

2022-08-24 12:57 UTC, ciripel commented on packages/crypto_assets/lib/src/networks_groups.dart
> +class TWCoinType {
moved in sio_core_light 1.0.2 in [7200809](https://github.com/SimplioOfficial/simplio-app/pull/144/commits/72008097081d3ad83eee584245b151f752980005)

2022-08-24 12:58 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +    late sio.Transaction rawTransaction;
fixed in [ab88a2f](https://github.com/SimplioOfficial/simplio-app/pull/144/commits/ab88a2f0b80fb7265b76e00bb1cba661f1407614)

2022-08-24 12:58 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +          walletAddress: _wallet.getAddressForCoin(networkId));
did not understand how to fix this

2022-08-24 12:59 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
fixed in [ab88a2f](https://github.com/SimplioOfficial/simplio-app/pull/144/commits/ab88a2f0b80fb7265b76e00bb1cba661f1407614)

2022-08-24 12:59 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +  Future<String> sendTransaction({
fixed in [ab88a2f](https://github.com/SimplioOfficial/simplio-app/pull/144/commits/ab88a2f0b80fb7265b76e00bb1cba661f1407614)

2022-08-25 08:21 UTC, jvrastil commented on lib/data/repositories/wallet_repository.dart
> +// import 'package:crypto_assets/crypto_assets.dart';
please remove unused import

2022-08-25 09:29 UTC, ciripel commented on lib/data/repositories/wallet_repository.dart
> +// import 'package:crypto_assets/crypto_assets.dart';
lol sure!

2022-08-25 11:13 UTC, ciripel commented
I have modified blockchain services responses to be exactly like i have asked today on `#backend-devs` channel on discord:
* broadcast 
```json
{
  "success": "bool",
  "errorMessage": "String?",
  "result": "String?" (null on error) 
}
```
* balance and balance-for-token
```json
{
  "address": "String",
  "contractAddress": "String?", (null if not token balance but coin balance)
  "balance": "int" (0 in case there is an error),
  "success": "bool",
  "errorMessage": "String?"
}
```
* history and history-for-token
```json
{
  "address": "String?" (null in case of solana token history),
  "contractAddress": "String?" (null in case of coin history and !null in case of token),
  "success": "bool",
  "errorMessage": "String?",
  "transactions": "List<Map<String|Dynamic>>?" (null in case of no transactions found or some error)
  [
    {
      "txtype": "String?",
      "address": "String?",
      "amount": "String?",
      "txId": "String?",
      "networkFee": "String?",
      "unixTime": "int?",
      "confirmed": "bool"
    }
  ]
}
```
* utils - utxoResponse
```json
{
  "items": "List<Map<String|Dynamic>>" (empty list and NOT null if there are no UTXOs) also empty list on ERRORS
  [
    {
      "txid": "String?",
      "vout": "int?",
      "value": "String?",
      "height": "int?",
      "confirmations": "int?",
      "scriptPubKey": "String?"
    }
  ],
  "success": "bool",
  "errorMessage": "String?"
}
```
* utils - ethereumResponse
```json
{
  "address": "String" (the address that was queried - also show it in case of error),
  "transactionCount": "String?" (null on errors),
  "success": "bool",
  "errorMessage": "String?"
}
```
* utils - solanaResponse
```json
{
  "lastBlockHash": "String?" (null in case of an error),
  "success": "bool",
  "errorMessage": "String?"
}
```

2022-08-26 11:55 UTC, jvrastil approved these changes
looks good to me now

2022-08-29 13:20 UTC, storkandstars approved these changes

2022-08-29 13:20 UTC, merged