Task/135 main app bar widget
SimplioOfficial/simplio-app pull request #154
Opened 2022-08-23 23:53 UTC by TomasPetrik

2022-08-29 13:26 UTC, storkandstars requested changes

2022-08-29 13:26 UTC, storkandstars commented on lib/view/app_bar/sio_app_bar.dart
> +import 'dart:ui';
reusable widgets should be located in the `view/widgets` folder.

2022-08-29 13:42 UTC, jvrastil requested changes

2022-08-29 13:42 UTC, jvrastil commented on lib/view/app_bar/sio_app_bar.dart
> +                    color: Colors.white,
can you use colors from `Theme` or at least `DarkMode`? So we don't forget about it when we refactor colors later...

(same goes with other colors in this file)

2022-08-29 13:42 UTC, jvrastil commented on lib/view/app_bar/sio_app_bar.dart
> +class SioAppBar extends StatelessWidget {
there is an error for smaller screen iphone SE3 (I tried it on iphone 13 pro max and it did not work as well...):
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/icon/profile_avatar_pic.png

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:658:14)
<asynchronous suspension>

Image provider: AssetImage(bundle: null, name: "assets/icon/profile_avatar_pic.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#40cb6(), name:
  "assets/icon/profile_avatar_pic.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by 177 pixels on the right.
```

![image](https://user-images.githubusercontent.com/44293042/187207541-3478493f-b361-4b4c-81bd-78cf1a6aa67d.png)

2022-08-29 13:42 UTC, jvrastil commented on lib/view/app_bar/sio_app_bar.dart
> +                              color: Theme.of(context).colorScheme.onPrimary)),
if you add comma after `style` it formats much better. (same for next `Text` widget)

2022-08-29 13:42 UTC, jvrastil commented on lib/view/app_bar/sio_app_bar.dart
> +                      if (subtitle != null) ...{
would there be a difference if you use the spread operator on array?

2022-08-29 13:42 UTC, jvrastil commented on lib/view/screens/discovery_screen.dart
> +                            //Text(context.locale.gamesTabBarLabel),
remove commented code please

2022-08-29 13:42 UTC, jvrastil commented on lib/view/widgets/bottom_tab_bar.dart
> +            )));
can you make it more compact by adding commas after each `)`?

2022-08-29 13:56 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +                    color: Colors.white,
It's good point, but actually this code will be removed in Task/136 branch.

2022-08-29 13:58 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +                              color: Theme.of(context).colorScheme.onPrimary)),
Okay.

2022-08-29 14:00 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +                      if (subtitle != null) ...{
There wouldn't be a difference in final but you are right. Array shoud be used instead.

2022-08-29 14:01 UTC, TomasPetrik commented on lib/view/widgets/bottom_tab_bar.dart
> +            )));
Yes, done.

2022-08-29 14:04 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +import 'dart:ui';
Okey. I moved this widget into view/widgets folder.

2022-08-29 14:37 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +class SioAppBar extends StatelessWidget {
It looks that it this png asset haven't been found so it broken whole app bar.

I changed image assets to be loaded fomr whole icon folder by:
- assets/icon/

It should works now.

2022-08-30 07:57 UTC, jvrastil approved these changes
looks good to me now 👍

2022-08-31 06:00 UTC, TomasPetrik commented on lib/view/app_bar/sio_app_bar.dart
> +import 'dart:ui';
Moved all pending widgets into view/widgets folder.

2022-08-31 08:56 UTC, storkandstars approved these changes

2022-08-31 09:05 UTC, merged