Completed task #171
SimplioOfficial/simplio-app pull request #183
Opened 2022-09-01 19:48 UTC by TomasPetrik

Incremented targetSdkVersion to 32,
Squashed commits.

2022-09-02 09:56 UTC, jvrastil requested changes

2022-09-02 09:56 UTC, jvrastil commented on lib/extensions/number_extensions.dart
> +    String currencySymbol = '\$',
do we plan to support only USD? @daxicek

2022-09-02 09:56 UTC, jvrastil commented on android/app/build.gradle
there is an issue with missing bottom bar when dropdown is opened

![image](https://user-images.githubusercontent.com/44293042/188114679-905f5254-d40f-4412-88fa-1436eae5b686.png)
![image](https://user-images.githubusercontent.com/44293042/188114704-3cf4dd57-b690-40b4-a6d8-632862a05db7.png)

2022-09-05 08:37 UTC, TomasPetrik commented on android/app/build.gradle
Fixed.

2022-09-05 09:02 UTC, daxicek commented on lib/extensions/number_extensions.dart
> +    String currencySymbol = '\$',
No, list of currencies is in system-assets endpoint.

2022-09-05 09:15 UTC, TomasPetrik commented on lib/extensions/number_extensions.dart
> +    String currencySymbol = '\$',
Ok, so this specific currency may be passed to currencySymbol as soon as we will have it defined in our data objects.

2022-09-07 17:10 UTC, ciripel approved these changes

2022-09-07 17:10 UTC, ciripel commented on lib/view/screens/discovery_screen.dart
> +          subtitle: 'User Level 1',
shouldn't the level be dynamic?

2022-09-07 19:08 UTC, TomasPetrik commented on lib/view/screens/discovery_screen.dart
> +          subtitle: 'User Level 1',
@ciripel 
Yes, you are right but this SioAppBar with leveling will be done in separated task.

2022-09-08 16:25 UTC, storkandstars requested changes

2022-09-08 16:25 UTC, storkandstars commented on lib/extensions/number_extensions.dart
> +import 'package:intl/intl.dart';
Move this extension folder to a relative domain. This specific extension will be used only inside the view layer. 
A. If it is specific to widgets. Move it to `widgets/extensions`
B. If it is specific to screens. Move it to `screens/extensions`
C. If it is specific to view in general. Move it to `view/extensions`. In that case consider if it is related to routes, themes, etc.

Each layer might have their mixins, extensions and other reusable components.

2022-09-08 16:25 UTC, storkandstars commented on lib/extensions/number_extensions.dart
> +    } else {
Tip: Omit unnecessary `else` when using `return` in previous condition block. It reduces nested code.

2022-09-08 16:25 UTC, storkandstars commented on lib/extensions/number_extensions.dart
> +    String formattedValue = getThousandSeparatedValue();
Allow ability to re-assignment value only when it is desired otherwise prefer making values `final`.

2022-09-09 06:46 UTC, TomasPetrik commented on lib/extensions/number_extensions.dart
> +import 'package:intl/intl.dart';
Okay. Moved it to view/extensions.

2022-09-09 06:48 UTC, TomasPetrik commented on lib/extensions/number_extensions.dart
> +    String formattedValue = getThousandSeparatedValue();
Fixed by using final.

2022-09-09 09:27 UTC, storkandstars approved these changes

2022-09-09 09:32 UTC, storkandstars approved these changes

2022-09-09 09:42 UTC, merged