Task/173 transaction item
SimplioOfficial/simplio-app pull request #186
Opened 2022-09-06 06:30 UTC by TomasPetrik

2022-09-12 12:58 UTC, storkandstars requested changes

2022-09-12 12:58 UTC, storkandstars commented on lib/extensions/date_extensions.dart
> +extension DateParse on DateTime {
Please, move this extension to `view/extensions` folder as it is related to view layer only

2022-09-12 12:58 UTC, storkandstars commented on lib/view/widgets/transaction_item.dart
> +import 'package:simplio_app/extensions/number_extensions.dart';
This extension should be inside `view/extensions` folder

2022-09-12 12:58 UTC, storkandstars commented on lib/view/widgets/transaction_item.dart
> +import 'package:simplio_app/extensions/date_extensions.dart';
This extension should be inside `view/extensions` folder

2022-09-12 12:58 UTC, storkandstars commented on pubspec.yaml
> +  infinite_scroll_pagination: ^3.2.0
Why do we use another package for pagination? We are able to achieve this easily inside flutter.

2022-09-12 13:25 UTC, TomasPetrik commented on lib/extensions/date_extensions.dart
> +extension DateParse on DateTime {
Done.

2022-09-12 13:26 UTC, TomasPetrik commented on lib/view/widgets/transaction_item.dart
> +import 'package:simplio_app/extensions/date_extensions.dart';
Yes. It was merged but not with proper file location. I will fix it.

2022-09-12 13:57 UTC, TomasPetrik commented on lib/view/widgets/transaction_item.dart
> +import 'package:simplio_app/extensions/number_extensions.dart';
I moved it there.

2022-09-13 07:26 UTC, storkandstars requested changes

2022-09-13 07:26 UTC, storkandstars commented on lib/logic/cubit/transactions/prices/transactions_cubit.dart
> +class TransactionsCubit extends Cubit<TransactionsState> {
Why is this file into sub-directory of transactions? `logic/cubit/transactions/prices`

2022-09-13 07:40 UTC, TomasPetrik commented on lib/logic/cubit/transactions/prices/transactions_cubit.dart
> +class TransactionsCubit extends Cubit<TransactionsState> {
Moved it to  logic/cubit/transactions/

2022-09-14 08:08 UTC, jvrastil requested changes
There is an error when going to `Transactions` tan and then to any other tab:
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Bad state: Cannot emit new states after calling close
#0      BlocBase.emit (package:bloc/src/bloc_base.dart:96:9)
#1      TransactionsCubit.loadTransactions (package:simplio_app/logic/cubit/transactions/transactions_cubit.dart:45:7)
<asynchronous suspension>
```

2022-09-14 09:33 UTC, TomasPetrik commented
> 

@jvrastil 

You can check it. It's fixed now.

2022-09-14 10:17 UTC, jvrastil approved these changes
looks good now

2022-09-14 10:31 UTC, storkandstars approved these changes

2022-09-14 10:43 UTC, merged