Task/172 balance widget
SimplioOfficial/simplio-app pull request #188
Opened 2022-09-09 06:43 UTC by TomasPetrik

2022-09-09 13:44 UTC, ciripel requested changes

2022-09-09 13:44 UTC, ciripel commented on lib/extensions/number_extensions.dart
> +extension DecimalParseExtension on Decimal {
We are against importing unnecessary packages into the application and more packages that can get discontinued.
Why do we need Decimal package? The application is not made to compute anything that can't be done with native types.
I propose creating instead a method that will make use of String manipulation for this widget.
Something like this will do:
```dart
String shiftDot({
  required String number,
  required int decimals,
  String char = '.',
}) {
  return '${number.substring(0, number.length - decimals)}$char'
      '${number.substring(number.length - decimals, number.length)}';
}
```

2022-09-09 15:21 UTC, TomasPetrik commented on lib/extensions/number_extensions.dart
> +extension DecimalParseExtension on Decimal {
@ciripel 
The method you mentioned here I already created which also supports inserting zeros before when decimals are greater than number length inself. Check toDecimalString() method.

But there was other problems and the main reason why I have imported this Decimal library was because we want do addition few large numbers with different decimals places. Some numbers might have 18 digits long decimal part. But I wanted to avoid doing it by double for two reasons:
1. double is loosing precision at some point , check https://pub.dev/packages/decimal ,
2. double doesn't support addition very big numbers.

In any finance applications I was working before we were using BigDecimal in Java, Kotlin, or any other languages regarding this reasons.

2022-09-09 17:45 UTC, ciripel commented on lib/extensions/number_extensions.dart
> +extension DecimalParseExtension on Decimal {
@TomasPetrik 

> The method you mentioned here I already created which also supports inserting zeros before when decimals are greater than number length inself. Check toDecimalString() method.

Excelent!


> But there was other problems and the main reason why I have imported this Decimal library was because we want do addition few large numbers with different decimals places. Some numbers might have 18 digits long decimal part. But I wanted to avoid doing it by double for two reasons:
> 
> 1. double is loosing precision at some point , check https://pub.dev/packages/decimal ,
> 2. double doesn't support addition very big numbers.
> 
> In any finance applications I was working before we were using BigDecimal in Java, Kotlin, or any other languages regarding this reasons.

Those problems do not apply in our case cause we will work will the smallest denominations only (Satoshi, lamports etc) so we will use `BigInt` because we will not use `division`, and `addition`, `subtract` and `multiply` they all return `BigInt`.
Manipulation of the data will be done in `BigInt` and after we will convert it in `String` to show it to the user.

2022-09-09 21:30 UTC, TomasPetrik commented on lib/extensions/number_extensions.dart
> +extension DecimalParseExtension on Decimal {
@ciripel 
After our conversation I did update to not using decimal dependency. Any calculations like adding numbers is done manually.

2022-09-09 21:53 UTC, ciripel approved these changes

2022-09-12 07:59 UTC, storkandstars requested changes

2022-09-12 07:59 UTC, storkandstars commented on test/data/model/currency_format_test.dart
> +import 'package:flutter_test/flutter_test.dart';
Please, move this file to `test/view/extensions/number_extensions.dart`

2022-09-12 08:21 UTC, storkandstars approved these changes

2022-09-12 08:22 UTC, merged