Task/196 coin detail screen
SimplioOfficial/simplio-app pull request #204
Opened 2022-09-19 09:14 UTC by TomasPetrik

Click on asset wallet, then choose any network wallet from expanded list.
It should open Coin Detail Screen with balance and transactions.

2022-09-19 10:53 UTC, jvrastil requested changes

2022-09-19 10:53 UTC, jvrastil commented on .github/workflows/run_tests_on_pull_request.yml
> +    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@master
can you please change it in `run_tests_on_push_test_branch.yml` in a similar way?

2022-09-19 10:53 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +                      builder: (state) => CoinDetailScreen(
There is already screen prepared for this -`AssetDetailScreen`. Please use that. Also please keep those buttons from bottom bar which are used to navigation to receive, send and other assets-related page...

2022-09-19 12:16 UTC, TomasPetrik commented on lib/view/routes/authenticated_router.dart
> +                      builder: (state) => CoinDetailScreen(
Okay. Done.

Yes I will keep this buttons with screens redirecting but in task/195 as it task was splitted.

2022-09-19 13:02 UTC, jvrastil commented on lib/view/routes/authenticated_router.dart
> +                      builder: (state) => CoinDetailScreen(
No, keep the bottom bar in master. I understand that there will be some changes in the UI but user needs to be able to navigate to sending and receiving assets.

2022-09-19 13:57 UTC, TomasPetrik commented on lib/view/routes/authenticated_router.dart
> +                      builder: (state) => CoinDetailScreen(
Ok I merged task/195 into this 196. You can check it out again.

2022-09-19 15:03 UTC, jvrastil requested changes

2022-09-19 17:21 UTC, TomasPetrik commented on lib/view/widgets/two_lines_app_bar.dart
> +                const SizedBox(),
No needed. Removed.

2022-09-19 17:25 UTC, TomasPetrik commented on lib/view/widgets/earning_elevated_button.dart
> +                                Text(
Okay. But as I saw this ThemedText doesn't have style bodyPrimary.

2022-09-19 17:54 UTC, TomasPetrik commented on lib/view/widgets/coin_details_menu.dart
> +              if (index == 0) ...{
There is no difference. It's just my personal habit adding curly braces while using if condition.

2022-09-20 06:45 UTC, TomasPetrik commented on lib/view/widgets/coin_details_menu.dart
> +              if (index == 0) ...{
But finally I removed this curly braces for reducing code.

2022-09-20 07:44 UTC, jvrastil approved these changes

2022-09-20 07:48 UTC, merged