Task/257 - Connect buy logic to UI
SimplioOfficial/simplio-app pull request #287
Opened 2022-10-24 07:57 UTC by jvrastil

- needs to be merged (and rebased) after https://github.com/SimplioOfficial/simplio-app/pull/281
- sign with apps@simplio.io
- use our test wallet because we are now on staging and using real money
- buy BUSD and check in explorer that money came

2022-10-28 12:22 UTC, TomasPetrik commented on lib/logic/cubit/asset_buy_form/asset_buy_form_state.dart
> +  double get estimatedPrice {
You can use fat arrow syntax like:
double get estimatedPrice ()=> buyConvertResponse.fiatAsset.amount /
        buyConvertResponse.cryptoAsset.amount;

2022-10-28 14:25 UTC, jvrastil commented on lib/logic/cubit/asset_buy_form/asset_buy_form_state.dart
> +  double get estimatedPrice {
fixed

2022-11-02 09:36 UTC, TomasPetrik commented on lib/view/widgets/success_page.dart
> +  final bool successButton;
Better name it like hasSuccessButton

2022-11-02 11:01 UTC, storkandstars commented on lib/view/screens/asset_buy_success_screen.dart
> +      successAction: () =>
Is that correct implementation? It doe not look right.

2022-11-02 12:34 UTC, jvrastil commented on lib/view/widgets/success_page.dart
> +  final bool successButton;
ok

2022-11-02 13:42 UTC, jvrastil commented on lib/view/screens/asset_buy_success_screen.dart
> +      successAction: () =>
it's intentional because you need to navigate user back to the screen detail. But I changed it so it's reusable also when user get to buy page from different locations

2022-11-02 13:43 UTC, jvrastil commented on lib/data/http/errors/bad_request_http_error.dart
> +class BadRequestHttpError extends Error {
it's not needed anymore, removed now

2022-11-02 14:04 UTC, storkandstars commented on lib/view/screens/asset_buy_success_screen.dart
> +      successAction: () =>
go router does not have popUntil method?

2022-11-02 14:05 UTC, storkandstars requested changes

2022-11-02 14:05 UTC, storkandstars commented on lib/data/http/errors/bad_request_http_error.dart
> +  BadRequestHttpError({
please make it constant

2022-11-02 14:31 UTC, jvrastil commented on lib/view/screens/asset_buy_success_screen.dart
> +      successAction: () =>
unfortunately no

2022-11-02 14:35 UTC, jvrastil commented on lib/data/http/errors/bad_request_http_error.dart
> +  BadRequestHttpError({
done

2022-11-03 08:44 UTC, storkandstars approved these changes

2022-11-03 08:52 UTC, merged