Completed task/269-search-coins-detail-ui
SimplioOfficial/simplio-app pull request #291
Opened 2022-10-24 14:03 UTC by TomasPetrik

add agreeement popup, Swap cancel/Do nothing buttons according to UX

2022-10-24 14:48 UTC, jvrastil requested changes

2022-10-24 14:48 UTC, jvrastil commented on lib/view/widgets/colorized_app_bar.dart
> -                  Navigator.of(context).pop();
I would rather keep this here and not to change the functionality every few commits.

2022-10-24 15:21 UTC, TomasPetrik commented on lib/view/widgets/colorized_app_bar.dart
> -                  Navigator.of(context).pop();
Ok. But then I have add it inside of two_lined_app_bar as well because of consistency.

2022-10-25 07:06 UTC, jvrastil approved these changes

2022-10-25 07:11 UTC, merged