Completed task/288-game-listing-with-game-detail
SimplioOfficial/simplio-app pull request #325
Opened 2022-11-07 08:24 UTC by TomasPetrik

# Overview

Create a game detail screen and list stored games in `my game` tab.

2022-11-07 10:28 UTC, jvrastil commented on android/app/src/main/AndroidManifest.xml
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
- there is an error in the console, when game detail is opened:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 173 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      PageController.page (package:flutter/src/widgets/page_view.dart:173:7)
#3      _SlidableGameImagesState.initState.<anonymous closure> (package:simplio_app/view/widgets/slidable_game_images.dart:35:25)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

```

- also should we display the picture large in case there is only one?
![image](https://user-images.githubusercontent.com/44293042/200287945-e2fc6762-a8bc-4d61-beea-da34c69502a7.png)

2022-11-07 10:40 UTC, jvrastil commented on lib/data/http/services/marketplace_service.dart
> +  WEB,
please use lower camel case for constant names

2022-11-07 10:40 UTC, jvrastil requested changes
please check the comments

2022-11-07 10:41 UTC, jvrastil commented on lib/logic/cubit/games/games_cubit.dart
> +  Future<bool> _hasCoinInWallet() async {
why do we need this?

2022-11-07 11:30 UTC, jvrastil commented on lib/view/widgets/game_detail_socials.dart
> +                    Expanded(
is it needed to combine expanded and shrinked sizedbox?

2022-11-08 08:42 UTC, TomasPetrik commented on lib/logic/cubit/games/games_cubit.dart
> +  Future<bool> _hasCoinInWallet() async {
Actually we dont need this , so I removed it.

2022-11-08 08:44 UTC, TomasPetrik commented on lib/view/widgets/game_detail_socials.dart
> +                    Expanded(
Okay, I replaced it by Spacer() . It makes more sense.

2022-11-08 08:49 UTC, TomasPetrik commented on lib/data/http/services/marketplace_service.dart
> +  WEB,
Okay, used @JsonValue as substitution.

2022-11-08 10:14 UTC, jvrastil commented on lib/view/widgets/my_games_content.dart
> +        child: BlocBuilder<GamesCubit, GamesState>(
there is one small bug - when the game is removed from My games this list is not updated

2022-11-08 11:28 UTC, TomasPetrik commented on lib/view/widgets/my_games_content.dart
> +        child: BlocBuilder<GamesCubit, GamesState>(
Fixed.

2022-11-08 11:35 UTC, jvrastil approved these changes
ok, works good now

2022-11-08 11:53 UTC, merged