Fixed bug/333-search-screens-are-scrollable
SimplioOfficial/simplio-app pull request #338
Opened 2022-11-09 09:22 UTC by TomasPetrik

Search input is not fixed and can be scrolled out of a view port on any search screen. The text field should be fixed on the top and only the fetched content should be scrollable.

2022-11-09 13:14 UTC, jvrastil requested changes

2022-11-09 13:14 UTC, jvrastil commented on lib/view/widgets/search.dart
>  import 'dart:ui';
there is strange issue - when you scroll up before you start to search and then search
![image](https://user-images.githubusercontent.com/44293042/200839808-31562502-4ca9-4778-96e2-e11da2de39e9.png)

2022-11-10 10:06 UTC, TomasPetrik commented on lib/view/widgets/search.dart
>  import 'dart:ui';
Fixed.

2022-11-10 10:55 UTC, jvrastil commented on lib/view/widgets/search.dart
>  import 'dart:ui';
good, it works

2022-11-10 10:55 UTC, jvrastil approved these changes

2022-11-10 11:18 UTC, merged