Refactor/373 refactor buy asset form
SimplioOfficial/simplio-app pull request #389
Opened 2022-11-18 17:31 UTC by jvrastil

2022-11-22 07:48 UTC, TomasPetrik commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_bloc.dart
> +    // print('CONVERTING VALUE');
Remove unused print() methods.
Even better use everytime printDebug()

2022-11-22 07:48 UTC, TomasPetrik commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_bloc.dart
> +    // print('ON VALUE SELECTED');
Remove commeted code.

2022-11-22 07:48 UTC, TomasPetrik commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_bloc.dart
> +    // print('ON VALUE CHANGED');
Same here.

2022-11-22 07:48 UTC, TomasPetrik commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_bloc.dart
> +    // print('Direction is: ${s.direction}');
Remove commented code.

2022-11-22 07:48 UTC, TomasPetrik commented on lib/view/authenticated_app.dart
>            create: (context) => AssetExchangeFormCubit(
So now we have 'AssetExchangeFormCubit' and 'AssetExchangeFormBloc' ?

Do we want to unify them to one Bloc ?

2022-11-22 07:48 UTC, TomasPetrik commented on lib/view/widgets/keypad.dart
> +const int numpadBehaviorRange = 1000;
You can use something like 'numpadReservedActionsOffset' or 'reservedActionsStartIndex'

2022-11-30 12:49 UTC, storkandstars requested changes

2022-11-30 12:49 UTC, storkandstars commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_bloc.dart
> +import 'package:crypto_assets/crypto_assets.dart';
remove this file for the PR

2022-11-30 12:49 UTC, storkandstars commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_event.dart
> +part of 'asset_exchange_form_bloc.dart';
remove this file for the PR

2022-11-30 12:49 UTC, storkandstars commented on lib/logic/bloc/asset_exchange_form/asset_exchange_form_state.dart
> +part of 'asset_exchange_form_bloc.dart';
remove this file for the PR

2022-11-30 12:49 UTC, storkandstars commented on lib/view/routes/authenticated_router.dart
> +                      builder: (state) => BlocProvider(
remove the bloc provider for exchange bloc

2022-11-30 12:49 UTC, storkandstars commented on lib/view/widgets/keypad.dart
> +const int numpadBehaviorRange = 1000;
remove the enum implementation for this PR

2022-11-30 12:49 UTC, storkandstars commented on lib/data/model/helpers/stringable_double.dart
> +import 'package:equatable/equatable.dart';
remove this type definition

2022-11-30 12:49 UTC, storkandstars commented on lib/data/repositories/wallet_repository.dart
> +        'inject father basket boss oyster kick cube enact novel tent liberty captain awesome title defense surround middle struggle clap milk notable carry exercise process';
REMOVE THIS !!!!!

2022-11-30 12:49 UTC, storkandstars commented on lib/data/http/services/swap_service.dart
> +  final double price;
This change is not used yet. remove it

2022-11-30 12:49 UTC, storkandstars commented on lib/data/http/services/buy_service.dart
> +class FiatAssetWithStringableDouble extends Equatable {
Stringable double is oboslete

2022-11-30 12:49 UTC, storkandstars commented on lib/view/routes/guards/protected_guard.dart
> +                  if (value == NumpadValue.erase) {
remove implementation of NumpadValue enum

2022-12-10 11:29 UTC, closed without merging