Task/375 create bubble on discovery page to show not backed up seed warning
SimplioOfficial/simplio-app pull request #526
Opened 2023-02-21 16:39 UTC by ciripel

2023-02-21 23:08 UTC, storkandstars requested changes

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +    final Color? leftColor,
left and right colors are not necessary here. we can have entire gradient as a input param or a just a list of colors. left and right colors are too specific.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/button/highlighted_elevated_button.dart
>      VoidCallback? onPressed,
flutter uses onTap terminology internally. i know we use onPressed on other locations but the bp is to use the one that is inside the flutter itself.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/button/highlighted_elevated_button.dart
>          ]),
please try to format the code with trailing commas in view layer to flatten the indentation.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/verified_notification_bubble.dart
> +class VerifiedNotificationBubble extends StatelessWidget with SnackBarMixin {
try to find a better name. bubble is not optimal. we might use AttentionContainer. widgets should be general and possibly be able to live in various contexts.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/verified_notification_bubble.dart
> +                      'We suggest you Verify your identity due to the use of all functionalities and full security of your Simplio app.',
we have translation files for that. .arb file has locale definitions

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/verified_notification_bubble.dart
> +                HighlightedElevatedButton.primary(
we do not to use the button itself here. i would suggest to make a input field `children` that will be inserted in Column widget. this solution help us to use widget composition on upper level (screens is where we mostly composite widgets) and we do not have widget to widget dependency.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/verified_notification_bubble.dart
> +                  leftColor: SioColors.attentionGradient,
within the #524 task we added a new type for primary button that achieve this behaviour.

2023-02-21 23:08 UTC, storkandstars commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +          leftColor ?? SioColors.highlight1,
please check #524 task where is a new primary button type to achieve this.

2023-02-21 23:10 UTC, storkandstars commented on lib/view/widgets/verified_notification_bubble.dart
> +                      'We suggest you Verify your identity due to the use of all functionalities and full security of your Simplio app.',
also do not use text translations inside a reusable widget. pass text with widget arguments.

2023-02-21 23:11 UTC, storkandstars commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +          leftColor ?? SioColors.highlight1,
https://github.com/SimplioOfficial/simplio-app/blob/f996c6d8b28079052175642df4f5b93791e0d8c2/lib/view/widgets/button/highlighted_elevated_button.dart#L16

2023-02-22 10:12 UTC, JiriBestak commented on lib/view/widgets/button/highlighted_elevated_button.dart
>      VoidCallback? onPressed,
okay, i will rename it

2023-02-22 10:20 UTC, JiriBestak commented on lib/view/widgets/button/highlighted_elevated_button.dart
>      VoidCallback? onPressed,
It is throughout the entire project, it will not be so easy to change and test it all

2023-02-22 10:21 UTC, JiriBestak commented on lib/view/widgets/button/highlighted_elevated_button.dart
>      VoidCallback? onPressed,
It is throughout the entire project, it will not be so easy to change and test it all

2023-02-22 10:32 UTC, JiriBestak commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +          leftColor ?? SioColors.highlight1,
is it in master? If no i will merge it after

2023-02-23 10:59 UTC, ciripel commented on lib/view/widgets/button/highlighted_elevated_button.dart
>      VoidCallback? onPressed,
No. Actually material package that is used for Android used exactly onPressed on his ElevatedButton(The widget we expand our HighLightedElevatedButton. 
Link here: https://github.com/flutter/flutter/blob/0c1ed759151a183078b21d970bf2547a26bcea82/packages/flutter/lib/src/material/elevated_button.dart#L69

2023-02-23 10:59 UTC, ciripel commented on lib/view/widgets/button/highlighted_elevated_button.dart
>          ]),
done in https://github.com/SimplioOfficial/simplio-app/pull/526/commits/5c8dc5bb60a3e89a4269a179794ab3087e656cc6.

2023-02-23 10:59 UTC, ciripel commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +    final Color? leftColor,
done in https://github.com/SimplioOfficial/simplio-app/pull/526/commits/5c8dc5bb60a3e89a4269a179794ab3087e656cc6.

2023-02-23 11:01 UTC, ciripel commented on lib/view/widgets/verified_notification_bubble.dart
> +                  leftColor: SioColors.attentionGradient,
we used this in https://github.com/SimplioOfficial/simplio-app/pull/526/commits/5c8dc5bb60a3e89a4269a179794ab3087e656cc6.

2023-02-23 11:01 UTC, ciripel commented on lib/view/widgets/button/highlighted_elevated_button.dart
> +          leftColor ?? SioColors.highlight1,
done in https://github.com/SimplioOfficial/simplio-app/pull/526/commits/5c8dc5bb60a3e89a4269a179794ab3087e656cc6.

2023-02-23 11:03 UTC, JiriBestak approved these changes

2023-02-23 13:35 UTC, storkandstars approved these changes

2023-02-23 13:36 UTC, merged