task/399-create-bubble-for-backup-screen
SimplioOfficial/simplio-app pull request #536
Opened 2023-03-10 08:51 UTC by ciripel

2023-03-10 09:25 UTC, JiriBestak approved these changes

2023-03-10 17:28 UTC, storkandstars requested changes

2023-03-10 17:28 UTC, storkandstars commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +                  Align(
Row and Column have main and cross axis alignment built in.

2023-03-10 17:28 UTC, storkandstars commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +                                setState(() {
We do not set local state here.

2023-03-10 17:28 UTC, storkandstars commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +          const SizedBox(
We might to replace these gaps within Gaps constants where we would define them e.g.`Gaps.vertical20`

2023-03-11 16:41 UTC, ciripel commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +                  Align(
fixed in https://github.com/SimplioOfficial/simplio-app/pull/536/commits/301c4d2cb601ecb1094f9542b0d56b9867c3e3f1

2023-03-11 16:41 UTC, ciripel commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +                                setState(() {
fixed in https://github.com/SimplioOfficial/simplio-app/pull/536/commits/301c4d2cb601ecb1094f9542b0d56b9867c3e3f1

2023-03-11 17:01 UTC, ciripel commented on lib/view/screens/authenticated_screens/backup_inventory_screen.dart
> +          const SizedBox(
fixed in https://github.com/SimplioOfficial/simplio-app/pull/536/commits/dd20181ab4fad37359c9811cea159e903cedd38d

2023-03-13 08:43 UTC, merged