Task/407 swap time out
SimplioOfficial/simplio-app pull request #554
Opened 2023-04-17 14:44 UTC by JiriBestak

2023-04-17 15:13 UTC, JiriVrbas-Eria commented on lib/logic/cubit/asset_swap_summary/asset_swap_summary_cubit.dart
> +      final isSwapTimeouted =
Dont need to create new variable. you can use if(_checkIfSwapIsTimeOuted(s.form.swapTimeout.toInt())){await _changeStateToTimeout(s);
        return;}

2023-04-17 15:13 UTC, JiriVrbas-Eria commented on lib/logic/cubit/asset_swap_summary/asset_swap_summary_cubit.dart
> +      final isSwapTimeouted =
Why is this check here again? If state is AssetSwapSummarySwapTimeout do we need to do this: _checkIfSwapIsTimeOuted(s.form.swapTimeout.toInt()) again? Why?

2023-04-17 15:13 UTC, JiriVrbas-Eria commented on lib/logic/cubit/asset_swap_summary/asset_swap_summary_cubit.dart
> +  bool _checkIfSwapIsTimeOuted(int responseTimeout) {
This can be named just _isSwapTimeouted

2023-04-17 15:13 UTC, JiriVrbas-Eria commented on lib/logic/cubit/asset_swap_summary/asset_swap_summary_cubit.dart
> +    if (dateTimeNowEpoch >= (responseTimeout * 1000)) {
you can simplify this return dateTimeNowEpoch >= (responseTimeout * 1000)

2023-04-17 15:13 UTC, JiriVrbas-Eria commented on lib/logic/cubit/asset_swap_summary/asset_swap_summary_cubit.dart
> +    final newSwapParams = await _getSwapParams(
What if swap params return error? How we handle it?

2023-04-18 10:57 UTC, JiriBestak commented on assets/icon/verified.png
no its not target. Its icon for success verification, i dont think its good idea name it like target. Maybe targetWithSuccessMark

2023-04-18 11:01 UTC, JiriBestak commented on assets/l10n/app_en.arb
> +  "asset_price_update_screen_title":"Price update",
i am not sure.  I think its from before when we had it like screen.

2023-04-18 11:02 UTC, JiriBestak commented on lib/logic/bloc/asset_swap_form/asset_swap_form_bloc.dart
> +        swapTimeout: SwapConvertSuccessResponse(res).value.swapTimeout
response and swapTimeout are properties of one object but i can create variable before and use it

2023-04-19 15:10 UTC, storkandstars requested changes

2023-04-20 06:23 UTC, ciripel commented on lib/logic/bloc/asset_swap_form/asset_swap_form_bloc.dart
> +        return;
fixed in https://github.com/SimplioOfficial/simplio-app/pull/554/commits/c8d793f5415740e9cde4c693045edc42c15e9304

2023-04-20 06:23 UTC, ciripel commented on lib/logic/bloc/asset_swap_form/asset_swap_form_bloc.dart
> +          swapTimeout: BigInt.from(0)));
fixed in https://github.com/SimplioOfficial/simplio-app/pull/554/commits/c8d793f5415740e9cde4c693045edc42c15e9304

2023-04-20 06:23 UTC, ciripel commented on lib/logic/bloc/asset_swap_form/asset_swap_form_bloc.dart
>          emit(SwapConverted(
fixed in https://github.com/SimplioOfficial/simplio-app/pull/554/commits/c8d793f5415740e9cde4c693045edc42c15e9304

2023-04-20 06:24 UTC, merged